### ISSUE TITLE
Improving the README.md

### ISSUE THREAD

**Issue by villivald** [villivald/villivald#1]
Need some fresh ideas for improving Readme.md - styling, stats, any kinds of visual stuff, etc. I am open to all suggestions 🙂. Feel free to make a pull request.

**villivald/villivald is a special repository. Its README.md will appear on [my public profile](https://github.com/villivald)!**

**Comment by sathiraumesh** [comment]
can I work on this

**Comment by Knackie** [comment]
Hi, can you assign me to this ? i'll make a great readme :)
